# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec para LIBRYNO v2.0."""
import os
import sys
from PyInstaller.utils.hooks import collect_data_files, collect_submodules

a = Analysis(
    ['src/main.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('src/ui/i18n/*.json', 'src/ui/i18n'),
        ('src/ui/themes/*.qss', 'src/ui/themes'),
        ('img', 'img'),
        ('.env.example', '.'),
    ],
    hiddenimports=[
        'src',
        'src.config',
        'src.core',
        'src.core.database',
        'src.core.models',
        'src.core.migrations',
        'src.core.seed',
             'src.auth',
        'src.auth.ordob_client',
        'src.auth.session',
        'src.auth.license',
        'src.sync',
        'src.sync.sync_manager',
        'src.features',
        'src.features.books',
        'src.features.readers',
        'src.features.collaborators',
        'src.features.loans',
        'src.features.reports',
        'src.features.notifications',
        'src.features.backup',
        'src.features.catalog',
        'src.features.import_data',
        'src.utils.sse_client',
        'src.ui',
        'src.ui.screens',
        'src.ui.screens.login',
        'src.ui.screens.home',
        'src.ui.widgets',
        'src.ui.widgets.toast',
        'src.ui.widgets.premium_badge',
        'src.ui.themes',
        'src.ui.themes.theme_manager',
        'src.ui.i18n',
        'src.ui.i18n.translator',
        'src.utils',
        'src.utils.constants',
        'src.utils.logger',
        'src.utils.crypto',
        'src.utils.validators',
        'src.utils.excel_export',
        'src.utils.isbn_api',
        'src.utils.image_optimizer',
        'src.utils.sse_client',
        'src.utils.system_theme',
        'bcrypt',
        'sqlalchemy',
        'sqlalchemy.dialects.sqlite',
        'loguru',
        'reportlab',
        'schedule',
        'keyring',
        'pandas',
        'matplotlib',
        'openpyxl',
        'requests',
        'requests_sse',
        'darkdetect',
        'json',
        'threading',
        'time',
        'atexit',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='LIBRYNO',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='img/icon.png',
)
